# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Gutenberg HTML5
description:
version: 0.0.01
logo: site-logo.svg # place in _includes/svg/
social-image: og-image.jpg # place in src/img/
# url: "https://www.mysite.com"
# analytics-code: UA-XXXXX-Y
# maps-api: ########

# Favicon settings - use realfavicon generator
icon-color: '#e08524'
msapplication-TileColor: '#222222'
theme-color: '#222222'

# Build settings
permalink: pretty
destination: public
source: src
markdown: kramdown
plugins:
  - jekyll-feed

sass:
  style: compressed # possible values: nested expanded compact compressed

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Exclude from processing.
#
# Don't forget that Jekyll automatically
# excludes files with a dot prefix
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - readme.md
  - jekyll-ignored/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

include:
  - _redirects # for netlify

# keep_files: []
