# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jer's Jekyll Template
description:
analytics-code: UA-XXXXX-Y

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  style: compact # possible values: nested expanded compact compressed

# Exclude from processing.
#
# Don't forget that Jekyll automatically
# excludes files with a dot prefix
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - readme.md
  - jekyll-ignored/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# keep_files: []
