# Site settings
title: Jekyll Gutenberg HTML5
tagline:
  en: 'EN tagline'
  fr: 'FR tagline'
description:
  en: 'EN desc'
  fr: 'FR desc'
social-image: og-image.jpg # place in src/img/

version: 0.0.01
url: "https://jekyll-gutenberg-html5.netlify.com"
# analytics-code: UA-XXXXX-Y
# maps-api: ########

# Favicon settings - use realfavicon generator
icon-color: '#e08524'
msapplication-TileColor: '#222222'
theme-color: '#222222'

# Build
source: src
destination: dist
permalink: pretty
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

sass:
  style: compressed # possible values: nested expanded compact compressed

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

include: [ "_redirects" ]
exclude: [ "jekyll-ignored/"]

plugins:
  - jekyll-feed
  - jekyll-polyglot

# Polyglot
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["assets", '_redirects', '404.html', 'browserconfig.xml', 'robots.txt']
parallel_localization: false
